// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Supabase's pooler
    // (pgbouncer, transaction mode) doesn't support the prepared statements
    // `prisma migrate` relies on. The app itself connects via DATABASE_URL
    // (pooled) through the driver adapter in src/lib/prisma.ts instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
